@startuml
'https://plantuml.com/class-diagram

' Del 1
class Main
class System
class User
class KitchenStaff
class Manager
class Waiter

' Del 2
class Menu
class KitchenMenu
class ManagerMenu
class WaiterMenu

' Del 3
class Table {
    int tableID
    String tableName
    TableType tableType
    double Amount
    LocalDate openingTime
    LocalDate closingTime
    ArrayList<Order> orders

    void addOrder()
    void removeOrder()
    void printOrder()
    void getInvoice()
    void printReservation()
}
enum TableType {
    AVAILABLE
    BUSY
    RESERVED
}
class Customer {
    String name
    String phone
    String review
}
class Reservation {
    LocalDate reservationTime
    int personCount
}

class Order {
    int OrderID
    int OrderLineID
    int tableID
    int menuID
    double price
    OrderStatus orderstatus

}

enum OrderStatus{
    ACTIVE
    READY
    CANCELLED
}

class Notes {
    Arraylist<String> notes
    void addNotes()
}
class Invoice {
    int InvoiceID
    LocalDate InvoiceDate
    int orderID
    double totalAmount
    void printInvoice()
}

' Del 4
class MenuCard {
    ArrayList<Item> discountedItems
}
class FoodCard
class DessertCard
class Item
class Dish
class DrinkCard
class Drink
class Ingredient
class StatReport

Main *-- System
System *-- User
User --|> KitchenStaff
User --|> Manager
User --|> Waiter
System *-- Menu
Menu --|> KitchenMenu
Menu --|> ManagerMenu
Menu --|> WaiterMenu
System *-- MenuCard
System *-- Table
TableType --* Table
Table o-- Order
Order o-- Notes
OrderStatus --* Order
Table o-- Customer
Table o-- Invoice
Table o-- Reservation
System o-- StatReport
MenuCard ..|> FoodCard
FoodCard *-- Dish
MenuCard ..|> DessertCard
DessertCard *-- Dish
MenuCard ..|> DrinkCard
DrinkCard *-- Drink
Item --|> Dish
Item --|> Drink
Dish *-- Ingredient
Drink *-- Ingredient

@enduml